---
- name: Create instances
  os_server:
    cloud: openstack
    name: "{{ item[0].name }}"
    image: "{{ item[0].image }}"
    key_name: "{{ item[0].key_name }}"
    flavor: "{{ item[0].flavor }}"
    security_groups: "{{ item[0].security_group }}"
    delete_fip: yes
    wait: no
    nics: 
      - net-name: "{{ item[0].net_name }}"
    userdata: "{{ item[0].userdata }}"

    meta: #"{{ item.meta }}"
      - group: "{{ item[1].group }}"
      - deployment_name: "{{ item[1].deployment_name }}"
        #loop: "{{ item.meta }}"
        #loop_control:
        #loop_var: my_meta

  with_nested:
    - "{{ osp_servers }}"
    - "{{ osp_servers.meta }}"

- name: Add floating IP to instance
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item.name }}"
    network: "{{ item.float_ip }}"
    wait: true
    timeout: 200
  with_items:
    - "{{ osp_servers }}"
