---
- name: Create instances
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    key_name: "{{ item.key_name }}"
    flavor: "{{ item.flavor }}"
    security_groups: "{{ item.security_group }}"
    delete_fip: yes
    wait: no
    nics: 
      - net-name: "{{ item.net_name }}"
    userdata: "{{ item.userdata }}"

    meta: "group={{ item.meta.group }},deployment_name={{ item.meta.deployment_name }}"

  loop: "{{ osp_servers }}"
  #loop: "{{ osp_servers | subelements('meta')|list }}"
  #with_nested:
  #  - "{{ osp_servers }}"
  #  - "{{ osp_servers|('meta)|list }}"

- name: Add floating IP to instance
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item.name }}"
    network: "{{ item.float_ip }}"
    wait: true
    timeout: 200
  with_items:
    - "{{ osp_servers }}"
